spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_demo
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:

  mapper-locations: classpath:mapper/*.xml
